FROM jenkins/jenkins:lts

USER root

# Install Docker & Docker Compose
RUN apt-get update && apt-get install -y docker.io docker-compose

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Use custom entrypoint to modify jenkins user at container runtime
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
